source "https://rubygems.org"

gem "yorobot"


gem "sportdb-readers"
gem "sportdb-exporters"


### note active record for now needs 
#  Error loading the 'sqlite3' Active Record adapter.
#    Missing a gem it depends on? 
#    Could not find 'sqlite3' (~> 1.4)
gem 'sqlite3', '~> 1.4'



